# Generated by Django 2.1.7 on 2020-12-03 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201130_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 3, 17, 47, 37, 221891)),
        ),
    ]
