# Generated by Django 2.1.7 on 2020-12-03 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201203_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 3, 18, 8, 25, 724747)),
        ),
    ]
